config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :scripts, only: %i[index show new create update] do
    member do
      # get :location
      resources :locations, only: %i[show create update]
      resources :plans, only: %i[show create update]
    end
  end

  resources :blueprints, only: %i[index show]

  patch '/scripts/:id', to: 'scripts#update'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blueprint.rb
# frozen_string_literal: true

class Blueprint < ApplicationRecord
  has_many :scripts
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :prompt_template, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :script
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :script
end

app/models/script.rb
class Script < ApplicationRecord
  belongs_to :user
  belongs_to :blueprint
  has_one :location
  has_one :plan
  validates :topic, presence: true
  validates :topic, length: { minimum: 2 }
  validates :topic, length: { maximum: 100 }

  # broadcast_replace_to(:notifications, target: "icon", html: "<span class='icon'>notification_new</span>")
  def regenerate_script
    self.script_body = ChatgptService.call("
      Rewrite the following 'technical script' for a YouTube video about #{topic}:
      '#{script_body}'
      Make sure the new version has a #{tone} tone, and the video made from this script should be #{duration} minutes long.")
    save
    # add turbo stream to view
    # add turbo frame to show
    # broadcast_to
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :scripts
  has_one_attached :avatar
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username avatar])
  end
end

app/controllers/blueprints_controller.rb
# frozen_string_literal: true

# app/controllers/blueprints_controller.rb
class BlueprintsController < ApplicationController
  before_action :set_blueprint, only: [:show]

  def index
    @blueprints = Blueprint.all
  end

  def show
    @script = Script.new
  end

  private

  # def blueprint_params
  #   params.require(:blueprint).permit(:name, :description)
  # end

  def set_blueprint
    @blueprint = Blueprint.find(params[:id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[show create update]

  def show
    @pexels_videos = pexels(@location.script.topic)
    @plan = @location.script.plan
    if @location.content.blank?
      response = ChatgptService.call("Give me a list of 5 non-specific locations (for example: 'Park' instead 'Central Park, New York')  to film a video that is based on following script:
      #{@location.script.script_body}
      Just give an enumerated list of locations, without a prefacing paragraph, specify what should be the content to record.
      Write it as HTML, using only h4, h5, and p tags in HTML code but don't include the head tag.")
      @location.update(content: response)
      fill_plan(@plan)
      render :show
    else
      respond_to do |format|
        fill_plan(@plan)
        format.html
        format.text { render :show, locals: { location: @location, plan: @plan }, formats: [:html] }
      end
    end
  end

  def create; end

  # PATCH/PUT /scripts/:script_id/locations/:id
  def update; end

  private

  def location_params
    params.require(:location).permit(:content)
  end

  def set_location
    @location = Location.find(params[:id])
  end

  def pexels(topic)
    Pexels::Client.new.videos.search(topic,
                                    page: 1, per_page: 6, size: :medium, orientation: :landscape)
  end

  def fill_plan(plan)
    if plan.content.blank?
      response = ChatgptService.call("Give me a step by step work plan to record and edit the youtube video based on following script:
        '#{@plan.script.script_body}'
        The plan's goal is to make the video easier to record and edit.
        I want to record all of the scenes that take place in sequence, rather than recording in the order of the script.
        Just give the working plan without a prefacing paragraph. Write it as HTML, using only h4, h5, and p tags in HTML code but don't include the head tag.")
      plan.update(content: response)
    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home; end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[show create update]

  def show
    if @plan.content.blank?
      response = ChatgptService.call("Give me only step by step itinerary to film the youtube video based on following script:
        #{@plan.script.script_body}
        Just give an itinerary without a prefacing paragraph and postscript and Note: ")
      @plan.update(content: response)
      render :show
    else
      respond_to do |format|
        format.html
        format.text { render :show, locals: { plan: @plan }, formats: [:html] }
      end
    end
  end

  def create; end

  def update; end

  private

  def plan_params
    params.require(:plan).permit(:content)
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end
end

app/controllers/scripts_controller.rb
# frozen_string_literal: true

require_relative '../jobs/get_ai_response_job'
# app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: %i[show update]
  skip_before_action :verify_authenticity_token

  def index
    @scripts = Script.where(user: current_user)
  end

  def show
    @pexels_videos = pexels(@script.topic)
    @script.update(location: Location.create) if @script.location.nil?
    @script.update(plan: Plan.create) if @script.plan.nil?
    if @script.script_body.blank?
      GetAiResponseJob.perform_later(@script)
      flash[:notice] = 'Script is being generated'
      render :show
    else
      respond_to do |format|
        format.html
        format.text { render :show, locals: { script: @script }, formats: [:html] }
      end
    end
  end

  def create
    @script = Script.new(script_params)
    @script.user = current_user
    @script.script_body = ''
    if @script.save
      redirect_to script_path(@script)
    else
      render 'blueprints/show'
    end
  end

  def update
    # raise
    @pexels_videos = pexels(@script.topic)

    # Check for script regeneration
    if script_params[:script_body].blank?
      GetAiResponseJob.perform_later(@script)
      flash[:notice] = 'Script is being regenerated'
      render :show
      return
    end

    # Update script details
    if @script.update(script_params)
      respond_to do |format|
        format.html { redirect_to scripts_path }
        format.text { render :show, locals: { script: @script }, formats: [:html] }
      end
    else
      flash[:alert] = 'Script was not successfully updated'
      render :show
    end
  end

  private

  def script_params
    params.require(:script).permit(:name, :topic, :tone, :duration, :blueprint_id, :pexels_videos, :script_body)
  end

  def set_script
    @script = Script.find(params[:id])
  end

  def pexels(topic)
    Pexels::Client.new.videos.search(topic,
                                    page: 1, per_page: 6, size: :medium, orientation: :landscape)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/blueprints/_blueprint.html.erb
<div class="col-sm-12 col-md-6 col-lg-4 mb-4">
  <%= link_to blueprint_path(blueprint) do %>
    <div class="card text-dark">
      <!-- White Tab for Text -->
      <div class="card-header">
        <div class="card-title-container">
          <h4 class="card-title mt-0 ">
            <p><%= blueprint.name %></p>
          </h4>
        </div>
      </div>
      <!-- Picture -->
      <div class="d-flex justify-content-center">
        <%= image_tag(blueprint.sampleimage, alt: "Blueprint Sample Image", style: "width: 80%") %>
      </div>
    </div>
  <% end %>
</div>

app/views/blueprints/index.html.erb
<div class="background-script py-3">
    <div class="blueprints-index">
        <div class="container storylab-container-cream col-9">
          <div class="row">
            <h1>Take a look at our video blueprints</h1>
            <p>These are tried and true formulas of videos to make your own.</p>
          </div>
          <div class="row">
            <% @blueprints.each do |blueprint| %>
              <%= render blueprint %>
            <% end %>
          </div>
        </div>
    </div>
</div>

app/views/blueprints/show.html.erb
<div>
  <div class="storylab-container-dark col-12 container my-3">
    <div class="storylab-container-gold d-flex">
      <div class="col-4 storylab-container-cream d-flex justify-content-center">
        <%= image_tag(@blueprint.sampleimage, alt: "Blueprint Sample Image", style: "width: 100%; height: auto;") %>
      </div>
      <div class="col-8 storylab-container-gold v-flex align-items-center justify-content-center">
        <lead><%= 'short intro' %></lead>
        <h1><%= @blueprint.name %></h1>
        <p><%= @blueprint.description %></p>
      </div>
    </div>
    <div class="d-flex" style="column-gap: 4px;">
      <div class="storylab-container-gold mt-3 col-7">
        <h5>Here's some videos</h5>
        <p>that use this formula</p>
        <div data-controller="video-player" data-target="thumbnails">
          <div class="d-flex justify-content-between my-4">
            <% @blueprint.sample_videos.each do |video| %>
              <%= image_tag "https://i.ytimg.com/vi/#{video}/hqdefault.jpg",
          id: "#{video}",
          class: "small-thumbnail",
          data: { action: "click->video-player#play"} %>
            <% end %>
          </div>
          <iframe class="py-2" data-video-player-target="video" src="" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen autoplay loop muted playsinline></iframe>
        </div>
      </div>
      <div class="storylab-container-cream mt-3 col-5">
        <h4>Make your own</h4>
        <p>Select the options and tell us what your video will be about</p>
        <%= simple_form_for [@blueprint, @script], url: scripts_path do |f| %>
          <%= f.input :topic,label: "Topic" %>
          <%= f.input :name,label: "Title of video" %>
        <br>
        <!-- Duration Slider -->
        <div class="form-group">
        <%= f.label :duration, "Duration (in minutes)", class: "option-label" %>
            <div class="slider-container">
                  <%= f.input_field :duration, type: 'range', list: 'tickmarks', step: 3, min: 3, max: 15, value: 3, class: 'form-control-range' %>
                  <datalist id="tickmarks">
                    <option value="3">
                    <option value="5">
                    <option value="7">
                    <option value="9">
                    <option value="12">
                  </datalist>
                  <div class="slider-labels">
                    <span>3</span>
                    <span>5</span>
                    <span>7</span>
                    <span>9</span>
                    <span>12</span>
                  </div>
            </div>
        </div>
        <br>
          <!-- Tone Radio Buttons -->
        <div class="form-group" >
          <%= f.label :tone, "Tone", class: "option-label" %>
            <br>
            <br>
            <div class="radio-columns">
              <div class="form-check">
                <%= f.radio_button :tone, "1", class: 'form-check-input' %>
                <%= f.label :tone, "Cheerful", value: "1", class: 'form-check-label' %>
              </div>
              <div class="form-check">
                <%= f.radio_button :tone, "2", class: 'form-check-input' %>
                <%= f.label :tone, "Educational", value: "2", class: 'form-check-label' %>
              </div>
              <div class="form-check">
                <%= f.radio_button :tone, "3", class: 'form-check-input' %>
                <%= f.label :tone, "Emotional", value: "3", class: 'form-check-label' %>
              </div>
              <div class="form-check">
                <%= f.radio_button :tone, "4", class: 'form-check-input' %>
                <%= f.label :tone, "Humorous", value: "4", class: 'form-check-label' %>
              </div>
              <div class="form-check">
                <%= f.radio_button :tone, "5", class: 'form-check-input' %>
                <%= f.label :tone, "Inspirational", value: "5", class: 'form-check-label' %>
              </div>
              <div class="form-check">
                <%= f.radio_button :tone, "6", class: 'form-check-input' %>
                <%= f.label :tone, "Neutral", value: "6", class: 'form-check-label' %>
              </div>
              <div class="form-check">
                <%= f.radio_button :tone, "7", class: 'form-check-input' %>
                <%= f.label :tone, "Playful", value: "7", class: 'form-check-label' %>
              </div>
            </div>
          <%= f.hidden_field :blueprint_id, value: @blueprint.id %>
          <%= f.submit 'generate', :class => 'spinner', :id => 'submit-button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<!-- app/views/locations/show.html.erb -->
<div class="background-script py-3">
  <div class="container col-12">
    <div class="storylab-container-gold mb-3">
      <h1><%= @location.script.name.capitalize %></h1>
      <p class="mb-0"><%= @location.script.blueprint.name.capitalize %></p>
    </div>
    <%# placeholders for real buttons %>
    <div class="d-flex justify-content-start mb-3">
      <%= link_to script_path(@location.script) do %>
        <%# <div class="storylab-container-gold">Script</div> %>
        <button class="btn-tab-inactive">Script</button>
      <% end %>
      <%= link_to location_path(@location) do %>
        <%# <div class="storylab-container-gold mx-3">Resources</div> %>
        <button class="btn-tab mx-3">Resources</button>
      <% end %>
    </div>
    <div class="storylab-container-gold d-flex">
      <div id="nil" class="col-4">
        <div class="storylab-container-cream">
          <h2>Free stock videos</h2>
          <p>for your project</p>
          <p>(Click to download)</p>
          <div class="col">
            <% @pexels_videos.each do |vid| %>
              <div class="d-flex justify-content-center mb-3">
                <div class="light-gold-div">
                  <% hd_video = vid.files.find { |file| file.quality == 'sd' } %>
                  <% video_url = hd_video.link %>
                  <%= link_to video_url, target: :_blank do %>
                    <%= video_tag video_url, size: "320x240", controls: false, autoplay: :autoplay, muted: :muted, loop: :loop, class: "rounded-video" %>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
          <span class="footer__logo__text__opaque">— Beautiful free videos from Pexels.</span>
        </div>
      </div>
      <div class="col-8 storylab-container-dark v-flex align-items-center justify-content-center">
        <div class="storylab-container-cream">
          <h1>Recommended locations</h1>
          <p>to shoot your video.</p>
          <%= raw @location.content.gsub("\n\n", "<br>") %>
        </div>
        <div class="mt-4 storylab-container-cream">
          <h1>Work plan</h1>
          <p>Follow these instructions to make your project easier.</p>
          <%= raw @plan.content.gsub("\n\n", "<br>") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div data-controller="background-switch">
  <div data-background-switch-target="main-page" data-action="onload->background-switch#toggle">
  <div class="home-text">
        <%= image_tag("storylabfull2.png", width: "100%", class: "center-image") %>
    <br>
    <br>
    <%= link_to "See our video blueprints", blueprints_path, class: "btn btn-home", id: 'submit-button' %>
  </div>
    <div class="background-image-container">
      <div class="row">
        <div data-background-switch-target="block1" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1563053581-1a7a69f8f656?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
        <div data-background-switch-target="block2" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1613294326794-e7c74fe886e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
        <div data-background-switch-target="block3" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1526915303387-35900bc4ff33?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
        <div data-background-switch-target="block4" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1629204814140-42a737865119?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
      </div>
      <div class="row">
        <div data-background-switch-target="block5" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1630797160666-38e8c5ba44c1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
        <div data-background-switch-target="block6" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1489395131208-596c1ecb2a39?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
        <div data-background-switch-target="block7" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1621763540919-1a0477861102?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
        <div data-background-switch-target="block8" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1611467377461-acbc2c9d3a06?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
      </div>
      <div class="row">
        <div data-background-switch-target="block9" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1577864662891-c7b77f10f638?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
        <div data-background-switch-target="block10" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1594394489098-74ac04c0fc2e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
        <div data-background-switch-target="block11" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1632820324313-ee2704746bfd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
        <div data-background-switch-target="block12" class="black-background col-3 background-matrix">
          <img src="https://images.unsplash.com/photo-1632923892506-8bcd4aa1a92b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80" class="d-block w-100 faded-banner" alt="...">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/plans/show.html.erb
<div class="container">
  <h1>Recording plans</h1>
  <% if @plan %>
    <%= raw @plan.content.gsub("\n", "<br>") %>
  <% else %>
    <p>Plan not found.</p>
  <% end %>
</div>

app/views/scripts/show.html.erb
<%# app/views/scripts/show.html.erb %>
<div class="background-script py-3">
  <div class="container col-12">
    <div class="storylab-container-gold mb-3">
      <h1><%= @script.name.capitalize %></h1>
      <p class="mb-0"><%= @script.blueprint.name.capitalize %></p>
    </div>
    <%# placeholders for real buttons %>
    <div class="d-flex justify-content-start mb-3">
      <%= link_to script_path(@script) do %>
        <%# <div class="storylab-container-gold">Script</div> %>
        <button class="btn-tab">Script</button>
      <% end %>
      <%= link_to location_path(@script.location) do %>
        <%# <div class="storylab-container-gold mx-3">Resources</div> %>
        <button class="btn-tab-inactive mx-3">Resources</button>
      <% end %>
    </div>
    <div class="storylab-container-gold d-flex">
      <div class="storylab-container-dark col-8" data-controller="editable-text">
        <form data-controller="clipboard">
          <div class="storylab-container-cream">
            <div class="script-body" data-controller="replace" data-replace-script-id-value="<%= @script.id %>" data-replace-target="scriptBody">
              <%= render 'scripts/script_body', script: @script %>
            </div>
          </div>
          <div class="button-submit">
          <br>
            <button type="submit" class="btn-readscript" data-action="editable-text#enableEditMode" data-editable-text-target="editButton">Edit</button>
            <button type="button" class="btn-readscript" data-action="clipboard#copy" data-clipboard-target="trigger"><i class="fa-regular fa-copy"></i></button>
          </div>
        </form>
      </div>
      <div class="col-4">
        <div class="storylab-container-cream", id="storylab-container-spacing">
          <div class="card-options">
            <div class="container-options">
              <h2>Options</h2>
              <br>
              <%= simple_form_for [@script], url: script_path(@script) do |f| %>
                <!-- Duration Slider -->
                <div class="form-group">
                  <%= f.label :duration, "Duration (in minutes)", class: "option-label" %>
                  <br>
                  <br>
                  <div class="slider-container">
                    <%= f.input_field :duration, type: 'range', list: 'tickmarks', step: 3, min: 3, max: 15, value: 3, class: 'form-control-range' %>
                    <datalist id="tickmarks">
                      <option value="3"></option>
                      <option value="5"></option>
                      <option value="7"></option>
                      <option value="9"></option>
                      <option value="12"></option>
                    </datalist>
                    <div class="slider-labels">
                      <span>3</span>
                      <span>5</span>
                      <span>7</span>
                      <span>9</span>
                      <span>12</span>
                    </div>
                  </div>
                </div>
                <!-- Tone Radio Buttons -->
                <br>
                <div class="form-group">
                  <%= f.label :tone, "Tone", class: "option-label" %>
                  <br>
                  <br>
                  <div class="radio-columns">
                    <div class="form-check">
                      <%= f.radio_button :tone, "1", class: 'form-check-input' %>
                      <%= f.label :tone, "Cheerful", value: "1", class: 'form-check-label' %>
                    </div>
                    <div class="form-check">
                      <%= f.radio_button :tone, "2", class: 'form-check-input' %>
                      <%= f.label :tone, "Educational", value: "2", class: 'form-check-label' %>
                    </div>
                    <div class="form-check">
                      <%= f.radio_button :tone, "3", class: 'form-check-input' %>
                      <%= f.label :tone, "Emotional", value: "3", class: 'form-check-label' %>
                    </div>
                    <div class="form-check">
                      <%= f.radio_button :tone, "4", class: 'form-check-input' %>
                      <%= f.label :tone, "Humorous", value: "4", class: 'form-check-label' %>
                    </div>
                    <div class="form-check">
                      <%= f.radio_button :tone, "5", class: 'form-check-input' %>
                      <%= f.label :tone, "Inspirational", value: "5", class: 'form-check-label' %>
                    </div>
                    <div class="form-check">
                      <%= f.radio_button :tone, "6", class: 'form-check-input' %>
                      <%= f.label :tone, "Neutral", value: "6", class: 'form-check-label' %>
                    </div>
                    <div class="form-check">
                      <%= f.radio_button :tone, "7", class: 'form-check-input' %>
                      <%= f.label :tone, "Playful", value: "7", class: 'form-check-label' %>
                    </div>
                  </div>
                  <br>
                  <%= f.submit 'regenerate', :class => 'spinner', :id => 'submit-button' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "storylab_no_copy.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user&.avatar&.attached? %>
            <%= cl_image_tag current_user.avatar.key, width: 40, height: 40, :gravity=>"face", :crop=>"thumb", class: "avatar", alt: "dropdown menu" %>
          <% else %>
              <%= image_tag "https://t4.ftcdn.net/jpg/00/23/72/59/240_F_23725944_W2aSrg3Kqw3lOmU4IAn7iXV88Rnnfch1.jpg", class: "avatar-generic" %>
          <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Scripts", scripts_path, class: "dropdown-item" %>
              <%= link_to "Blueprints", blueprints_path, class: "dropdown-item" %>
              <% if (script = current_user&.scripts&.last) %>
                <%= link_to "Last Used Blueprint", blueprint_path(script.blueprint_id), class: "dropdown-item" %>
              <% end %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>